source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZJSocketLib_Example', :exclusive => true do
  pod 'ZJSocketLib', :path => '../'
end

target 'ZJSocketLib_Tests', :exclusive => true do
  pod 'ZJSocketLib', :path => '../'

  
end
